export { About } from './About'
export { Intro } from './Intro'
export { Navbar} from './Navbar'
export { NotFound } from './NotFound'
export { Projects } from './Projects'
export { Posts } from './Posts'
export { Contact } from './Contact' 